# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18949cfc173db05f08c728f43ffd6a06aca7a842e3d5bf2dee7aaf5321f76f498f215d81a7f6cb485bde36f2234e6a961aec91047a32ba0aa5a763f90c36675c

test:
  secret_key_base: 7ff9fdcf7677764d23e3166747dff69a4b3b939154f624b1c18ef131bb3018319f8dae88ea1f79347ec03aad38b770ca2946330ba9ff38d403c3d2a8ab5af67e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
